### ISSUE TITLE
images.phenotype.org returns urllib.error.HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by Dorky-Lever** [mpi2/LAMA#16]
Hi everyone, 

I've been just recently having trouble with downloading the walkthrough data due to 403 errors. Is there any urllib headers that can work around the 403 issue? 

Kind Regards, 
Kyle Drover

This is run below (I've added print(url) within download_and_extract_zip). 

[kd0793@gadi-login-09 ~]$ lama_get_walkthrough_data
Downloading data
http://images.mousephenotype.org/lama/lama_walkthroughs.zip
Traceback (most recent call last):
  File "/home/801/kd0793/.local/bin/lama_get_walkthrough_data", line 11, in <module>
    sys.exit(main())
  File "/home/801/kd0793/.local/lib/python3.6/site-packages/lama/scripts/lama_get_walkthrough_data.py", line 18, in main
    download_and_extract_zip(url, unzip_dir)
  File "/home/801/kd0793/.local/lib/python3.6/site-packages/lama/common.py", line 887, in download_and_extract_zip
    remotezip = urllib.request.urlopen(url)
  File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib64/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

[kd0793@gadi-login-09 ~]$ curl -i http://images.mousephenotype.org/lama/lama_walkthroughs.zip
HTTP/1.1 403 Forbidden
Date: Tue, 04 Aug 2020 03:29:32 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/5.6.38
Content-Length: 228
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /lama/lama_walkthroughs.zip
on this server.</p>
</body></html>

**Comment by Dorky-Lever** [comment]
Nevermind this was due to an issue with the computing cluster (was trying to download into a write protected folder).
