### ISSUE TITLE
lama_convert_16_to_8 : 'Namespace' object has no attribute 'clobber'

### ISSUE THREAD

**Issue by Dorky-Lever** [mpi2/LAMA#19]
Hi everyone, 

I'm getting the following error when running lama_convert_16_to_8: 

[kd0793@gadi-login-02 ark_test]$ lama_convert_16_to_8 -i inputs --clobber
usage: Rescale 16 bit images to 8bit [-h] -i [INDIR [INDIR ...]] [-o OUTDIR]
Rescale 16 bit images to 8bit: error: unrecognized arguments: --clobber
[kd0793@gadi-login-02 ark_test]$ lama_convert_16_to_8 -i inputs -o dont --clobber
usage: Rescale 16 bit images to 8bit [-h] -i [INDIR [INDIR ...]] [-o OUTDIR]
Rescale 16 bit images to 8bit: error: unrecognized arguments: --clobber
[kd0793@gadi-login-02 ark_test]$ lama_convert_16_to_8 -i inputs -o inputs_casted
Traceback (most recent call last):
  File "/home/801/kd0793/.local/bin/lama_convert_16_to_8", line 11, in <module>
    sys.exit(main())
  File "/home/801/kd0793/.local/lib/python3.6/site-packages/lama/utilities/lama_convert_16_to_8.py", line 54, in main
    if args.outdir and args.clobber:
AttributeError: 'Namespace' object has no attribute 'clobber'

I'll see if I can fix the namespace up. 

Kind Regards, 
Kyle Drover

**Comment by Dorky-Lever** [comment]
So far have changed the args to: 
parser = argparse.ArgumentParser("Rescale 16 bit images to 8bit")
    parser.add_argument('-i', '--indir', dest='indirs', help='dir with vols to convert. Will include subdirectories', required=True,  nargs='*')
    parser.add_argument('-o', '--outdir', dest='outdir', help='dir to put vols in. Omit to overwtrite source and use --clobber', required=False,
                        default=None)
    parser.add_argument('-c', '--clobber', dest='clobber', help='force overwriting of input volumes', action='store_true', default=None)

but now getting a new error: 
Namespace(clobber=True, indirs=['inputs'], outdir=None)
Traceback (most recent call last):
  File "/home/801/kd0793/.local/bin/lama_convert_16_to_8", line 11, in <module>
    sys.exit(main())
  File "/home/801/kd0793/.local/lib/python3.6/site-packages/lama/utilities/lama_convert_16_to_8.py", line 65, in main
    convert_16_bit_to_8bit(indirs, outdir, args.clobber)
  File "/home/801/kd0793/.local/lib/python3.6/site-packages/lama/utilities/lama_convert_16_to_8.py", line 11, in convert_16_bit_to_8bit
    paths = common.get_file_paths(Path(indir))
  File "/usr/lib64/python3.6/pathlib.py", line 1001, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/lib64/python3.6/pathlib.py", line 656, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib64/python3.6/pathlib.py", line 640, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not list


Why is the input directory recursive?

**Comment by Dorky-Lever** [comment]
Closed as its not an issue on the dev branch
